# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/datawidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataWidget(object):
    def setupUi(self, DataWidget):
        DataWidget.setObjectName("DataWidget")
        DataWidget.resize(1422, 837)
        self.verticalLayout = QtWidgets.QVBoxLayout(DataWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topPanel = QtWidgets.QWidget(DataWidget)
        self.topPanel.setEnabled(True)
        self.topPanel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topPanel.setObjectName("topPanel")
        self.topPanelLayout = QtWidgets.QHBoxLayout(self.topPanel)
        self.topPanelLayout.setObjectName("topPanelLayout")
        self.label = QtWidgets.QLabel(self.topPanel)
        self.label.setObjectName("label")
        self.topPanelLayout.addWidget(self.label)
        self.cmbDataset = QtWidgets.QComboBox(self.topPanel)
        self.cmbDataset.setEnabled(False)
        self.cmbDataset.setMinimumSize(QtCore.QSize(200, 0))
        self.cmbDataset.setObjectName("cmbDataset")
        self.topPanelLayout.addWidget(self.cmbDataset)
        self.cmbChallenge = QtWidgets.QComboBox(self.topPanel)
        self.cmbChallenge.setEnabled(False)
        self.cmbChallenge.setMinimumSize(QtCore.QSize(130, 0))
        self.cmbChallenge.setObjectName("cmbChallenge")
        self.topPanelLayout.addWidget(self.cmbChallenge)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topPanelLayout.addItem(spacerItem)
        self.cmbProtocol = QtWidgets.QComboBox(self.topPanel)
        self.cmbProtocol.setObjectName("cmbProtocol")
        self.cmbProtocol.addItem("")
        self.cmbProtocol.addItem("")
        self.topPanelLayout.addWidget(self.cmbProtocol)
        self.pbLoadDataset = QtWidgets.QPushButton(self.topPanel)
        self.pbLoadDataset.setObjectName("pbLoadDataset")
        self.topPanelLayout.addWidget(self.pbLoadDataset)
        self.pbLoadSession = QtWidgets.QPushButton(self.topPanel)
        self.pbLoadSession.setEnabled(False)
        self.pbLoadSession.setObjectName("pbLoadSession")
        self.topPanelLayout.addWidget(self.pbLoadSession)
        self.pbSaveSession = QtWidgets.QPushButton(self.topPanel)
        self.pbSaveSession.setEnabled(False)
        self.pbSaveSession.setObjectName("pbSaveSession")
        self.topPanelLayout.addWidget(self.pbSaveSession)
        self.pbPublish = QtWidgets.QPushButton(self.topPanel)
        self.pbPublish.setEnabled(False)
        self.pbPublish.setObjectName("pbPublish")
        self.topPanelLayout.addWidget(self.pbPublish)
        self.verticalLayout.addWidget(self.topPanel)
        self.bottomPanel = QtWidgets.QWidget(DataWidget)
        self.bottomPanel.setObjectName("bottomPanel")
        self.bottomPanelLayout = QtWidgets.QVBoxLayout(self.bottomPanel)
        self.bottomPanelLayout.setObjectName("bottomPanelLayout")
        self.mapAndPlotPanel = QtWidgets.QWidget(self.bottomPanel)
        self.mapAndPlotPanel.setMinimumSize(QtCore.QSize(0, 300))
        self.mapAndPlotPanel.setObjectName("mapAndPlotPanel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mapAndPlotPanel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_9 = QtWidgets.QWidget(self.mapAndPlotPanel)
        self.widget_9.setMinimumSize(QtCore.QSize(350, 0))
        self.widget_9.setMaximumSize(QtCore.QSize(260, 16777215))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dataTreeWidget = QtWidgets.QTreeWidget(self.widget_9)
        self.dataTreeWidget.setMinimumSize(QtCore.QSize(340, 0))
        self.dataTreeWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.dataTreeWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.dataTreeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dataTreeWidget.setUniformRowHeights(True)
        self.dataTreeWidget.setObjectName("dataTreeWidget")
        self.verticalLayout_4.addWidget(self.dataTreeWidget)
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pbDeleteMulti = QtWidgets.QPushButton(self.widget_10)
        self.pbDeleteMulti.setEnabled(False)
        self.pbDeleteMulti.setObjectName("pbDeleteMulti")
        self.horizontalLayout_7.addWidget(self.pbDeleteMulti)
        self.pbMoveTo = QtWidgets.QPushButton(self.widget_10)
        self.pbMoveTo.setEnabled(False)
        self.pbMoveTo.setObjectName("pbMoveTo")
        self.horizontalLayout_7.addWidget(self.pbMoveTo)
        self.pbEditLabelMulti = QtWidgets.QPushButton(self.widget_10)
        self.pbEditLabelMulti.setEnabled(False)
        self.pbEditLabelMulti.setMinimumSize(QtCore.QSize(100, 0))
        self.pbEditLabelMulti.setObjectName("pbEditLabelMulti")
        self.horizontalLayout_7.addWidget(self.pbEditLabelMulti)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.horizontalLayout.addWidget(self.widget_9)
        self.widget = QtWidgets.QWidget(self.mapAndPlotPanel)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout.setObjectName("gridLayout")
        self.infoWidget = QtWidgets.QWidget(self.widget_8)
        self.infoWidget.setMaximumSize(QtCore.QSize(16777215, 170))
        self.infoWidget.setObjectName("infoWidget")
        self.formLayout = QtWidgets.QFormLayout(self.infoWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.infoWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lblInstancelName = QtWidgets.QLabel(self.infoWidget)
        self.lblInstancelName.setText("")
        self.lblInstancelName.setObjectName("lblInstancelName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lblInstancelName)
        self.label_3 = QtWidgets.QLabel(self.infoWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lblInstanceLabel = QtWidgets.QLabel(self.infoWidget)
        self.lblInstanceLabel.setText("")
        self.lblInstanceLabel.setObjectName("lblInstanceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lblInstanceLabel)
        self.label_4 = QtWidgets.QLabel(self.infoWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lblInstanceURI = QtWidgets.QLabel(self.infoWidget)
        self.lblInstanceURI.setText("")
        self.lblInstanceURI.setObjectName("lblInstanceURI")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lblInstanceURI)
        self.label_5 = QtWidgets.QLabel(self.infoWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lblInstanceWidth = QtWidgets.QLabel(self.infoWidget)
        self.lblInstanceWidth.setText("")
        self.lblInstanceWidth.setObjectName("lblInstanceWidth")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lblInstanceWidth)
        self.label_6 = QtWidgets.QLabel(self.infoWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lblInstanceHeight = QtWidgets.QLabel(self.infoWidget)
        self.lblInstanceHeight.setText("")
        self.lblInstanceHeight.setObjectName("lblInstanceHeight")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lblInstanceHeight)
        self.label_7 = QtWidgets.QLabel(self.infoWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lblInstanceDate = QtWidgets.QLabel(self.infoWidget)
        self.lblInstanceDate.setText("")
        self.lblInstanceDate.setObjectName("lblInstanceDate")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lblInstanceDate)
        self.gridLayout.addWidget(self.infoWidget, 0, 0, 1, 1)
        self.paintingWidget = QtWidgets.QWidget(self.widget_8)
        self.paintingWidget.setObjectName("paintingWidget")
        self.paintingLayout = QtWidgets.QVBoxLayout(self.paintingWidget)
        self.paintingLayout.setObjectName("paintingLayout")
        self.gridLayout.addWidget(self.paintingWidget, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setStyleSheet("height:2px")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout.addWidget(self.widget)
        self.labelsGroup = QtWidgets.QGroupBox(self.mapAndPlotPanel)
        self.labelsGroup.setMinimumSize(QtCore.QSize(250, 0))
        self.labelsGroup.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelsGroup.setFont(font)
        self.labelsGroup.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.labelsGroup.setObjectName("labelsGroup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.labelsGroup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.labelsGroup)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrallAreaWidget = QtWidgets.QWidget()
        self.scrallAreaWidget.setGeometry(QtCore.QRect(0, 0, 218, 668))
        self.scrallAreaWidget.setObjectName("scrallAreaWidget")
        self.labelButtonsLayout = QtWidgets.QVBoxLayout(self.scrallAreaWidget)
        self.labelButtonsLayout.setContentsMargins(12, -1, -1, -1)
        self.labelButtonsLayout.setObjectName("labelButtonsLayout")
        self.scrollArea.setWidget(self.scrallAreaWidget)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.labelsGroup)
        self.bottomPanelLayout.addWidget(self.mapAndPlotPanel)
        self.verticalLayout.addWidget(self.bottomPanel)

        self.retranslateUi(DataWidget)
        QtCore.QMetaObject.connectSlotsByName(DataWidget)

    def retranslateUi(self, DataWidget):
        _translate = QtCore.QCoreApplication.translate
        DataWidget.setWindowTitle(_translate("DataWidget", "Form"))
        self.label.setText(_translate("DataWidget", "Dataset"))
        self.cmbProtocol.setItemText(0, _translate("DataWidget", "coco"))
        self.cmbProtocol.setItemText(1, _translate("DataWidget", "scikitlearn"))
        self.pbLoadDataset.setText(_translate("DataWidget", "Load dataset"))
        self.pbLoadSession.setText(_translate("DataWidget", "Load session"))
        self.pbSaveSession.setText(_translate("DataWidget", "Save session"))
        self.pbPublish.setText(_translate("DataWidget", "Publish"))
        self.dataTreeWidget.headerItem().setText(0, _translate("DataWidget", "Section"))
        self.pbDeleteMulti.setText(_translate("DataWidget", "Delete"))
        self.pbMoveTo.setText(_translate("DataWidget", "Move To"))
        self.pbEditLabelMulti.setText(_translate("DataWidget", "Edit Label"))
        self.label_2.setText(_translate("DataWidget", "Name:"))
        self.label_3.setText(_translate("DataWidget", "Label"))
        self.label_4.setText(_translate("DataWidget", "URI"))
        self.label_5.setText(_translate("DataWidget", "Width"))
        self.label_6.setText(_translate("DataWidget", "Height"))
        self.label_7.setText(_translate("DataWidget", "Date Captured"))
        self.labelsGroup.setTitle(_translate("DataWidget", "Labels"))

