# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/datawidget.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DataWidget(object):
    def setupUi(self, DataWidget):
        DataWidget.setObjectName("DataWidget")
        DataWidget.resize(1384, 837)
        self.verticalLayout = QtWidgets.QVBoxLayout(DataWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topPanel = QtWidgets.QWidget(DataWidget)
        self.topPanel.setEnabled(True)
        self.topPanel.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topPanel.setObjectName("topPanel")
        self.topPanelLayout = QtWidgets.QHBoxLayout(self.topPanel)
        self.topPanelLayout.setObjectName("topPanelLayout")
        self.label = QtWidgets.QLabel(self.topPanel)
        self.label.setObjectName("label")
        self.topPanelLayout.addWidget(self.label)
        self.cmbDataset = QtWidgets.QComboBox(self.topPanel)
        self.cmbDataset.setEnabled(False)
        self.cmbDataset.setMinimumSize(QtCore.QSize(200, 0))
        self.cmbDataset.setObjectName("cmbDataset")
        self.topPanelLayout.addWidget(self.cmbDataset)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topPanelLayout.addItem(spacerItem)
        self.pbLoadDataset = QtWidgets.QPushButton(self.topPanel)
        self.pbLoadDataset.setObjectName("pbLoadDataset")
        self.topPanelLayout.addWidget(self.pbLoadDataset)
        self.pbPublish = QtWidgets.QPushButton(self.topPanel)
        self.pbPublish.setEnabled(False)
        self.pbPublish.setObjectName("pbPublish")
        self.topPanelLayout.addWidget(self.pbPublish)
        self.verticalLayout.addWidget(self.topPanel)
        self.bottomPanel = QtWidgets.QWidget(DataWidget)
        self.bottomPanel.setObjectName("bottomPanel")
        self.bottomPanelLayout = QtWidgets.QVBoxLayout(self.bottomPanel)
        self.bottomPanelLayout.setObjectName("bottomPanelLayout")
        self.mapAndPlotPanel = QtWidgets.QWidget(self.bottomPanel)
        self.mapAndPlotPanel.setMinimumSize(QtCore.QSize(0, 300))
        self.mapAndPlotPanel.setObjectName("mapAndPlotPanel")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mapAndPlotPanel)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_9 = QtWidgets.QWidget(self.mapAndPlotPanel)
        self.widget_9.setMinimumSize(QtCore.QSize(350, 0))
        self.widget_9.setMaximumSize(QtCore.QSize(260, 16777215))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dataTreeWidget = QtWidgets.QTreeWidget(self.widget_9)
        self.dataTreeWidget.setMinimumSize(QtCore.QSize(340, 0))
        self.dataTreeWidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.dataTreeWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.dataTreeWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dataTreeWidget.setUniformRowHeights(True)
        self.dataTreeWidget.setObjectName("dataTreeWidget")
        self.verticalLayout_4.addWidget(self.dataTreeWidget)
        self.widget_10 = QtWidgets.QWidget(self.widget_9)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pbDeleteMulti = QtWidgets.QPushButton(self.widget_10)
        self.pbDeleteMulti.setEnabled(False)
        self.pbDeleteMulti.setObjectName("pbDeleteMulti")
        self.horizontalLayout_7.addWidget(self.pbDeleteMulti)
        self.pushButton = QtWidgets.QPushButton(self.widget_10)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.pbEditLabelMulti = QtWidgets.QPushButton(self.widget_10)
        self.pbEditLabelMulti.setEnabled(False)
        self.pbEditLabelMulti.setMinimumSize(QtCore.QSize(100, 0))
        self.pbEditLabelMulti.setObjectName("pbEditLabelMulti")
        self.horizontalLayout_7.addWidget(self.pbEditLabelMulti)
        self.verticalLayout_4.addWidget(self.widget_10)
        self.horizontalLayout.addWidget(self.widget_9)
        self.widget = QtWidgets.QWidget(self.mapAndPlotPanel)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout.setObjectName("gridLayout")
        self.imgLbl = QtWidgets.QLabel(self.widget_8)
        self.imgLbl.setText("")
        self.imgLbl.setObjectName("imgLbl")
        self.gridLayout.addWidget(self.imgLbl, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setStyleSheet("height:2px")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(700, 150))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 64))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_4 = QtWidgets.QWidget(self.widget_7)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineName = QtWidgets.QLineEdit(self.widget_4)
        self.lineName.setEnabled(False)
        self.lineName.setObjectName("lineName")
        self.horizontalLayout_2.addWidget(self.lineName)
        self.horizontalLayout_6.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_7)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_5)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cmbLabel = QtWidgets.QComboBox(self.widget_5)
        self.cmbLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLabel.sizePolicy().hasHeightForWidth())
        self.cmbLabel.setSizePolicy(sizePolicy)
        self.cmbLabel.setObjectName("cmbLabel")
        self.horizontalLayout_3.addWidget(self.cmbLabel)
        self.horizontalLayout_6.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_7)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget_6)
        self.label_5.setMinimumSize(QtCore.QSize(50, 0))
        self.label_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineSource = QtWidgets.QLineEdit(self.widget_6)
        self.lineSource.setEnabled(False)
        self.lineSource.setObjectName("lineSource")
        self.horizontalLayout_5.addWidget(self.lineSource)
        self.horizontalLayout_6.addWidget(self.widget_6)
        self.verticalLayout_5.addWidget(self.widget_7)
        self.widget_11 = QtWidgets.QWidget(self.widget_2)
        self.widget_11.setMinimumSize(QtCore.QSize(46, 0))
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pbDeleteSingle = QtWidgets.QPushButton(self.widget_11)
        self.pbDeleteSingle.setEnabled(False)
        self.pbDeleteSingle.setObjectName("pbDeleteSingle")
        self.horizontalLayout_8.addWidget(self.pbDeleteSingle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.pbCancelEdit = QtWidgets.QPushButton(self.widget_11)
        self.pbCancelEdit.setEnabled(False)
        self.pbCancelEdit.setObjectName("pbCancelEdit")
        self.horizontalLayout_8.addWidget(self.pbCancelEdit)
        self.pbUpdateSingle = QtWidgets.QPushButton(self.widget_11)
        self.pbUpdateSingle.setEnabled(False)
        self.pbUpdateSingle.setObjectName("pbUpdateSingle")
        self.horizontalLayout_8.addWidget(self.pbUpdateSingle)
        self.verticalLayout_5.addWidget(self.widget_11)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget)
        self.labelsGroup = QtWidgets.QGroupBox(self.mapAndPlotPanel)
        self.labelsGroup.setMinimumSize(QtCore.QSize(250, 0))
        self.labelsGroup.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelsGroup.setFont(font)
        self.labelsGroup.setAlignment(QtCore.Qt.AlignCenter)
        self.labelsGroup.setObjectName("labelsGroup")
        self.horizontalLayout.addWidget(self.labelsGroup)
        self.bottomPanelLayout.addWidget(self.mapAndPlotPanel)
        self.verticalLayout.addWidget(self.bottomPanel)

        self.retranslateUi(DataWidget)
        QtCore.QMetaObject.connectSlotsByName(DataWidget)

    def retranslateUi(self, DataWidget):
        _translate = QtCore.QCoreApplication.translate
        DataWidget.setWindowTitle(_translate("DataWidget", "Form"))
        self.label.setText(_translate("DataWidget", "Dataset"))
        self.pbLoadDataset.setText(_translate("DataWidget", "Load dataset"))
        self.pbPublish.setText(_translate("DataWidget", "Publish"))
        self.dataTreeWidget.headerItem().setText(0, _translate("DataWidget", "Section"))
        self.pbDeleteMulti.setText(_translate("DataWidget", "Delete"))
        self.pushButton.setText(_translate("DataWidget", "Move To"))
        self.pbEditLabelMulti.setText(_translate("DataWidget", "Edit Label"))
        self.label_2.setText(_translate("DataWidget", "Name"))
        self.label_3.setText(_translate("DataWidget", "Label"))
        self.label_5.setText(_translate("DataWidget", "Source"))
        self.pbDeleteSingle.setText(_translate("DataWidget", "Delete"))
        self.pbCancelEdit.setText(_translate("DataWidget", "Cancel"))
        self.pbUpdateSingle.setText(_translate("DataWidget", "Update"))
        self.labelsGroup.setTitle(_translate("DataWidget", "Labels"))

