# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgets/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1435, 1120)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolbarWidget = QtWidgets.QWidget(self.centralWidget)
        self.toolbarWidget.setMaximumSize(QtCore.QSize(90, 16777215))
        self.toolbarWidget.setObjectName("toolbarWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.toolbarWidget)
        self.verticalLayout.setContentsMargins(5, 0, 5, 20)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbData = QtWidgets.QPushButton(self.toolbarWidget)
        self.pbData.setMinimumSize(QtCore.QSize(80, 80))
        self.pbData.setMaximumSize(QtCore.QSize(80, 80))
        self.pbData.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pbData.setText("")
        self.pbData.setIconSize(QtCore.QSize(64, 64))
        self.pbData.setCheckable(True)
        self.pbData.setObjectName("pbData")
        self.verticalLayout.addWidget(self.pbData)
        self.pbTrain = QtWidgets.QPushButton(self.toolbarWidget)
        self.pbTrain.setMinimumSize(QtCore.QSize(80, 80))
        self.pbTrain.setMaximumSize(QtCore.QSize(80, 80))
        self.pbTrain.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pbTrain.setText("")
        self.pbTrain.setIconSize(QtCore.QSize(64, 64))
        self.pbTrain.setCheckable(True)
        self.pbTrain.setObjectName("pbTrain")
        self.verticalLayout.addWidget(self.pbTrain)
        self.pbTest = QtWidgets.QPushButton(self.toolbarWidget)
        self.pbTest.setMinimumSize(QtCore.QSize(80, 80))
        self.pbTest.setMaximumSize(QtCore.QSize(80, 80))
        self.pbTest.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pbTest.setText("")
        self.pbTest.setIconSize(QtCore.QSize(64, 64))
        self.pbTest.setCheckable(True)
        self.pbTest.setObjectName("pbTest")
        self.verticalLayout.addWidget(self.pbTest)
        self.pbDeploy = QtWidgets.QPushButton(self.toolbarWidget)
        self.pbDeploy.setMinimumSize(QtCore.QSize(80, 80))
        self.pbDeploy.setMaximumSize(QtCore.QSize(80, 80))
        self.pbDeploy.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pbDeploy.setText("")
        self.pbDeploy.setIconSize(QtCore.QSize(64, 64))
        self.pbDeploy.setCheckable(True)
        self.pbDeploy.setObjectName("pbDeploy")
        self.verticalLayout.addWidget(self.pbDeploy)
        self.pbGigaPOWER = QtWidgets.QPushButton(self.toolbarWidget)
        self.pbGigaPOWER.setMinimumSize(QtCore.QSize(80, 80))
        self.pbGigaPOWER.setMaximumSize(QtCore.QSize(80, 80))
        self.pbGigaPOWER.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pbGigaPOWER.setText("")
        self.pbGigaPOWER.setIconSize(QtCore.QSize(64, 64))
        self.pbGigaPOWER.setCheckable(True)
        self.pbGigaPOWER.setObjectName("pbGigaPOWER")
        self.verticalLayout.addWidget(self.pbGigaPOWER)
        spacerItem = QtWidgets.QSpacerItem(20, 432, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pbSettings = QtWidgets.QPushButton(self.toolbarWidget)
        self.pbSettings.setMinimumSize(QtCore.QSize(80, 80))
        self.pbSettings.setMaximumSize(QtCore.QSize(80, 80))
        self.pbSettings.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pbSettings.setText("")
        self.pbSettings.setIconSize(QtCore.QSize(64, 64))
        self.pbSettings.setCheckable(True)
        self.pbSettings.setObjectName("pbSettings")
        self.verticalLayout.addWidget(self.pbSettings)
        self.horizontalLayout.addWidget(self.toolbarWidget)
        self.mainStackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.mainStackedWidget.setObjectName("mainStackedWidget")
        self.pageData = QtWidgets.QWidget()
        self.pageData.setObjectName("pageData")
        self.mainStackedWidget.addWidget(self.pageData)
        self.pageTrain = QtWidgets.QWidget()
        self.pageTrain.setObjectName("pageTrain")
        self.mainStackedWidget.addWidget(self.pageTrain)
        self.pageTest = QtWidgets.QWidget()
        self.pageTest.setObjectName("pageTest")
        self.mainStackedWidget.addWidget(self.pageTest)
        self.pageDeploy = QtWidgets.QWidget()
        self.pageDeploy.setObjectName("pageDeploy")
        self.mainStackedWidget.addWidget(self.pageDeploy)
        self.pageGP = QtWidgets.QWidget()
        self.pageGP.setObjectName("pageGP")
        self.mainStackedWidget.addWidget(self.pageGP)
        self.horizontalLayout.addWidget(self.mainStackedWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1435, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.mainStackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbData.setToolTip(_translate("MainWindow", "Applications"))
        self.pbTrain.setToolTip(_translate("MainWindow", "Explorer"))
        self.pbTest.setToolTip(_translate("MainWindow", "Editor"))
        self.pbDeploy.setToolTip(_translate("MainWindow", "Analize"))
        self.pbGigaPOWER.setToolTip(_translate("MainWindow", "Analize"))
        self.pbSettings.setToolTip(_translate("MainWindow", "Settings"))

